/*
 * ActionDef.hpp
 *
 *  Created on: Nov 20, 2021
 *      Author: stanimir
 */

#ifndef GAME_ACTION_ACTIONDEF_HPP_
#define GAME_ACTION_ACTIONDEF_HPP_

enum class Action_t {
	NONE,
	MOVE_ACTION_START,
	MOVE_UP = MOVE_ACTION_START, MOVE_RIGHT, MOVE_DOWN, MOVE_LEFT,
	MOVE_ACTION_END = MOVE_LEFT,
	FIRE_ACTION_START,
	FIRE_UP = FIRE_ACTION_START, FIRE_RIGHT, FIRE_DOWN, FIRE_LEFT,
	FIRE_ACTION_END = FIRE_LEFT,
};

#endif /* GAME_ACTION_ACTIONDEF_HPP_ */
